name: realtime_client
description: Listens to changes in a PostgreSQL Database and via websockets.
  This is for usage with [Supabase Realtime](https://github.com/supabase/realtime) server.
version: 0.0.1-dev.2
homepage: "https://supabase.io"
repository: "https://github.com/supabase/realtime-dart"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  web_socket_channel: ^1.1.0

dev_dependencies:
  test: ^1.15.4
  lint: ^1.3.0
